### ISSUE TITLE
这个项目后续会合并到go arena吗？ 另外 go arena 已经试验很久后，后期会转正吗？

### ISSUE THREAD

**Issue by it512** [qiulaidongfeng/arena#1]

**Comment by qiulaidongfeng** [comment]
这个项目是我个人研究在go实现arena写的，和go标准库实现的实验性arena，支持的语义不同，不太可能合并进标准库。
go标准库的arena是否会结束实验转正，主要看这些问题是否得到解决

- API那样具有传染性，许多软件包在不更改其 API 来接受 arena 的情况下无法使用 arena。
- 能否容易的正确使用，比如如果引入arena导致有一种语法同时用于两种指针，一种是普通指针，不用担心突然指针指向的内存被释放，另一种是指向从arena分配内存的指针，指针指向的内存可能突然被释放，这样两种指针一种语法是不容易正确使用的。

**Comment by it512** [comment]
谢谢！
